# Generated by Django 4.0.1 on 2022-01-16 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Norte', 'Norte'), ('Nordeste', 'Nordeste'), ('Centro-Oeste', 'Centro Oeste'), ('Sudeste', 'Sudeste'), ('Sul', 'Sul')], max_length=12, unique=True)),
            ],
            options={
                'db_table': 'Region',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.region')),
            ],
            options={
                'db_table': 'Fruit',
                'ordering': ['name'],
            },
        ),
    ]
